### ISSUE TITLE
Should xs1 in lists -> reducing include 3?

### ISSUE THREAD

**Issue by ilkka** [seance/fp-patterns#2]
https://github.com/seance/fp-patterns/blob/master/specs/src/test/scala/lists.scala#L34 uses List.range and therefore doesn't include 3. Is this an intentional gotcha?

**Comment by seance** [comment]
Looks like I probably meant it to include 3, hence List.range(1, 4)

**Comment by seance** [comment]
Fixed in 4664bfa29a6e931614c3b9782af2e833ca588cea
